version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_app_prod
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: mix phx.server
    environment:
      MIX_ENV: prod
      DATABASE_URL: ecto://postgres:postgres@db:5432/my_app_prod
      SECRET_KEY_BASE: your_secret_key_here
    ports:
      - "4000:4000"
    depends_on:
      - db

volumes:
  db_data:
